CREATE TABLE TEST2
(
  TEST2ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  B       BOOLEAN                           NOT NULL
);
CREATE TABLE TEST
(
  TESTID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  S      CLOB,
  I      INTEGER,
  D      TIMESTAMP,
  TEST2  BIGINT,
  CONSTRAINT TEST_TEST2_TEST2ID_FK FOREIGN KEY (TEST2) REFERENCES TEST2 (TEST2ID)
);
CREATE TABLE PUBLIC.Kreuz
(
  KreuzID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Test    INTEGER                            NOT NULL,
  Test2   BIGINT                             NOT NULL,
  CONSTRAINT Kreuz_TEST_TESTID_fk FOREIGN KEY (Test) REFERENCES TEST (TESTID) ON UPDATE CASCADE,
  CONSTRAINT Kreuz_TEST2_TEST2ID_fk FOREIGN KEY (Test2) REFERENCES TEST2 (TEST2ID) ON UPDATE CASCADE
);
CREATE UNIQUE INDEX Kreuz_Test_Test2_uindex
  ON PUBLIC.Kreuz (Test, Test2);

INSERT INTO TEST2 (B) VALUES (0);
INSERT INTO TEST (S, I, D, TEST2) VALUES ('s', 1, '2017-05-13 16:42:43', 1);
INSERT INTO Kreuz (Test, Test2) VALUES (1, 1);